### ISSUE TITLE
Cannot override log-base in defaults.yaml

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-defaults#21]
Colcon only supports per-verb config options in defaults.yaml, and `--log-base`, `--log-level` are only accepted at the pre-verb stage.

This works: `colcon --log-base /dev/null list`
This fails with "unrecognized arguments": `colcon list --log-base /dev/null`
Adding this to `defaults.yaml` is silently ignored:
```
list:
  <<: *paths
  log-base: /dev/null
```

I expect that:
1. The order of arguments shouldn't matter
2. There should be some way of specifying `--log-base` in `colcon.yaml`
3. Ignored entries in `colcon.yaml` should not be silently ignored; there should be a visible warning message.

**Comment by dirk-thomas** [comment]
> The order of arguments shouldn't matter

The order does matter. The arguments before the verb `list` are handled by a different `argparse` parser than the ones after. That is simply how `argparse` works.

**Comment by rotu** [comment]
> The order does matter.

I know it does and I understand the technical reason why it does, but from an interaction standpoint, I don't think it *should*.

I think `action` and `argparse.REMAINDER` may be helpful in changing this: https://docs.python.org/3.8/library/argparse.html#argparse-remainder Or maybe intermixed parsing https://docs.python.org/3.8/library/argparse.html#intermixed-parsing Or `parse_known_args` https://docs.python.org/3.6/library/argparse.html#argparse.ArgumentParser.parse_known_args

**Comment by dirk-thomas** [comment]
I would rather not try to work around how `argparse` works. The logic to decorate the `argparse` parser is already pretty "sophisticated" (to say the least).  If you would like to contribute a pull request I am happy to review it. One note ahead of time: if the solution to this introduces a lot of complexity I will be inclined to not merge it to keep the maintenance overhead low.

**Comment by dirk-thomas** [comment]
Please see #22 which resolves bullet 2. and 3.

**Comment by rotu** [comment]
Excellent. Thank you!

**Comment by rotu** [comment]
FYI: here's how my colcon yaml file looks:
https://gist.github.com/rotu/62cccb11b25398e9d1aa45021376d546

All the paths being absolute means I can `colcon build` from anywhere without polluting the source tree

**Comment by dirk-thomas** [comment]
> here's how my colcon yaml file looks:

Interesting usage - thanks for sharing.

Regarding https://gist.github.com/rotu/62cccb11b25398e9d1aa45021376d546#file-colcon-yaml-L19-L20: it is less that `""` applies to all colcon subcommands but these are the arguments on the root parser (see `colcon --help` without a verb). There could be root-level arguments which don't apply to all verbs (none atm though).
