### ISSUE TITLE
Defaults for a workspace vs global

### ISSUE THREAD

**Issue by jdlangs** [colcon/colcon-defaults#27]
I'm interested in specifying defaults for all the packages in a workspace (e.g., `--merge-install`) without using command line arguments. I definitely don't have a thorough understanding of the colcon universe so maybe something to do this already exists, but all I saw were options to either set defaults globally or individually on package names/paths. It would seem pretty easy to have this package check for a `defaults.yaml` (`colcon_defaults.yaml`?) in the workspace root directory and apply those on top of the global defaults.

Is this something that would be desirable, assuming there isn't already a solution to the workspace default issue?

**Comment by dirk-thomas** [comment]
A workspace-level configuration file for additional defaults (similar to [additional metadata](https://github.com/colcon/colcon-metadata/blob/4bd198d6f6de24fbe6fc41e0498553b0a9ca2173/colcon_metadata/package_discovery/colcon_meta.py#L38-L45)) sounds like a useful feature. A pull request for this would be appreciated.

**Comment by jdlangs** [comment]
Sounds good. Would you recommend going the route of expanding `colcon-defaults` to look for another yaml file or changing `colcon-metadata`  so the `colcon.meta` file can work on the whole workspace?

**Comment by dirk-thomas** [comment]
Metadata are conceptionally different. So it should be within this package / repository looking for an additional yaml file in the root of the workspace.
